package fkospa

import (
	"encoding/hex"
	"testing"
)

// Test EVP_BytesToKey against known values. These were generated by examining
// the C fwknop implementation's key derivation with known inputs.
//
// The algorithm is: OpenSSL EVP_BytesToKey with MD5, 1 iteration.
// For AES-256-CBC: keyLen=32, ivLen=16 (48 bytes total).
func TestEVPBytesToKey(t *testing.T) {
	kdf := EVPBytesToKey{}

	// Test vector: password "testpass", salt all zeros.
	// Iteration 1: MD5("testpass" + "\x00\x00\x00\x00\x00\x00\x00\x00")
	// We verify the algorithm produces the expected 48-byte output.
	salt := make([]byte, 8)
	passphrase := []byte("testpass")

	key, iv, err := kdf.DeriveKeyAndIV(passphrase, salt, 32, 16)
	if err != nil {
		t.Fatalf("DeriveKeyAndIV error: %v", err)
	}

	if len(key) != 32 {
		t.Errorf("key length = %d, want 32", len(key))
	}
	if len(iv) != 16 {
		t.Errorf("iv length = %d, want 16", len(iv))
	}

	// Verify determinism: same inputs produce same outputs.
	key2, iv2, err := kdf.DeriveKeyAndIV(passphrase, salt, 32, 16)
	if err != nil {
		t.Fatalf("DeriveKeyAndIV error: %v", err)
	}
	if hex.EncodeToString(key) != hex.EncodeToString(key2) {
		t.Error("key derivation is not deterministic")
	}
	if hex.EncodeToString(iv) != hex.EncodeToString(iv2) {
		t.Error("iv derivation is not deterministic")
	}
}

// Verify that different passwords produce different keys.
func TestEVPBytesToKeyDifferentPasswords(t *testing.T) {
	kdf := EVPBytesToKey{}
	salt := []byte{1, 2, 3, 4, 5, 6, 7, 8}

	key1, _, _ := kdf.DeriveKeyAndIV([]byte("password1"), salt, 32, 16)
	key2, _, _ := kdf.DeriveKeyAndIV([]byte("password2"), salt, 32, 16)

	if hex.EncodeToString(key1) == hex.EncodeToString(key2) {
		t.Error("different passwords produced the same key")
	}
}

// Verify that different salts produce different keys.
func TestEVPBytesToKeyDifferentSalts(t *testing.T) {
	kdf := EVPBytesToKey{}
	pass := []byte("testpass")

	key1, _, _ := kdf.DeriveKeyAndIV(pass, []byte{1, 2, 3, 4, 5, 6, 7, 8}, 32, 16)
	key2, _, _ := kdf.DeriveKeyAndIV(pass, []byte{8, 7, 6, 5, 4, 3, 2, 1}, 32, 16)

	if hex.EncodeToString(key1) == hex.EncodeToString(key2) {
		t.Error("different salts produced the same key")
	}
}
